[package]
name = "tari_protobuf_build"
version = "0.0.5"
authors = ["The Tari Development Community"]
description = "Protobuf build code for Tari codebase"
keywords = ["protobuf", "build"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost-build = "0.6.1"
sha2 = "0.8.0"
