[clog]
# A repository link with the trailing '.git' which will be used to generate
# all commit and issue links
repository = "https://github.com/tari-project/tari"

# specify the style of commit links to generate, defaults to "github" if omitted
link-style = "github"
changelog = "changelog.md"
from-latest-tag = true
