# So, you want to update the Rust toolchain...

# Besides making sure the code compiles (duh) and the tests/clippy pass (obviously)
# Please note that you'll have to update all the toolchain references in the codebase!
# AND build new docker images for:
# - rust_tari-build-with-deps
# - rust-ndk
# AND update the action-buildlibs dockerfile.


# Hours spent updating the Rust Toolchain = 10
# other places to check:
# - the CI files in .github folder
# - the Makefile in base_layer/key_manager/Makefile
[toolchain]
channel = "nightly-2024-02-04"
