[package]
name = "tari_max_size"
version = "1.4.2-rc.1"
edition = "2021"
description = "Tari max size library"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
categories = ["cryptography"]
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
tari_utilities = { version = "0.7" }

borsh = "1.2"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
