[package]
name = "tari_comms_rpc_macros"
description = "RPC service proc macro"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.28.1"
edition = "2018"

[lib]
proc-macro = true

[dependencies]

proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = { version = "1.0.38", features = ["fold"] }

[dev-dependencies]
tari_comms = { version = "^0.28", path = "../", features = ["rpc"] }
tari_test_utils = { version = "^0.28", path = "../../infrastructure/test_utils" }

futures = "0.3.5"
prost = "0.9.0"
tokio = { version = "1", features = ["macros"] }
tower-service = "0.3"
