[package]
name = "tari_testnet_miner"
version = "0.1.0"
authors = ["Schalk van Heerden <sw@tari.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.8", features = ["std"] }
tonic = "0.1.0-alpha.3"
bytes = "0.4"
prost = "0.5"
tokio = "0.2.9"
futures= { version = "^0.3.1", default-features = false, features = ["alloc"]}
async-stream = "0.1.2"
http = "0.1"
tower = "=0.3.0-alpha.2"
clap = "2.33.0"
serde = { version = "1.0.101", features = ["derive"] }
config = { version = "0.9.3" }
env_logger = "0.7"
rand = "0.5.5"
digest = "0.8.1"
derive-error = "0.0.4"
bigint = "^4.4.1"
blake2 = "^0.8.0"
chrono = { version = "0.4.6", features = ["serde"]}

tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0"}
tari_common = {path = "../../common", version= "^0.0"}
tari_core = {path = "../../base_layer/core", version= "^0.0"}
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_transactions = { path = "../../base_layer/transactions", version = "^0.0" }

[build-dependencies]
tonic-build = "0.1.0-alpha.3"
