[package]
name = "tari_shutdown"
description = "A convenient shutdown signal"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.8.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3.1"

[dev-dependencies]
tokio = {version="^0.2", features=["rt-core"]}
