[package]
name = "taiji_chat_client"
authors = ["The Taiji Development Community"]
description = "Taiji cucumber chat client"
license = "BSD-3-Clause"
version = "0.52.0-pre.0"

edition = "2018"

[dependencies]
minotaiji_app_utilities = { path = "../../../../applications/minotaiji_app_utilities" }
taiji_common = { path = "../../../../common" }
taiji_common_sqlite = { path = "../../../../common_sqlite" }
taiji_common_types = { path = "../../../common_types" }
taiji_comms = { path = "../../../../comms/core" }
taiji_comms_dht = { path = "../../../../comms/dht" }
taiji_contacts = { path = "../../../contacts" }
taiji_p2p = { path = "../../../p2p" }
taiji_service_framework= { path = "../../../service_framework" }
taiji_shutdown = { path = "../../../../infrastructure/shutdown" }
taiji_storage = { path = "../../../../infrastructure/storage" }

anyhow = "1.0.41"
async-trait = "0.1.52"
config = { version = "0.13.0" }
diesel = { version = "2.0.3", features = ["sqlite", "r2d2", "serde_json", "chrono", "64-column-tables"] }
lmdb-zero = "0.4.4"
log = "0.4.17"
serde = "1.0.136"
