[package]
name = "minotari_wallet_grpc_client"
version = "0.1.0"
edition = "2021"
description = "Base node GRPC client"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
minotari_app_grpc = { path = "../../../applications/minotari_app_grpc" }
tari_common_types = { path = "../../../base_layer/common_types" }

thiserror = "1.0.35"
tonic = { version = "0.7.2", default-features = false, features = ["codegen", "transport", "tls"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
