[package]
name = "tari_stratum_transcoder"
authors = ["The Tari Development Community"]
description = "The tari stratum transcoder for miningcore"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.28.1"
edition = "2018"

[features]
default = []
envlog = ["env_logger"]

[dependencies]
tari_comms = { path = "../../comms" }
tari_app_grpc = { path = "../tari_app_grpc" }
tari_common = { path = "../../common" }
tari_core = { path = "../../base_layer/core", default-features = false, features = ["transactions"] }
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }
tari_utilities = "^0.3"

bincode = "1.3.1"
bytes = "0.5"
chrono = { version = "0.4.19", default-features = false }
config = { version = "0.9.3" }
env_logger = { version = "0.7.1", optional = true }
futures = "0.3.5"
hex = "0.4.2"
hyper = "0.14.12"
jsonrpc = "0.12.0"
log = { version = "0.4.8", features = ["std"] }
rand = "0.7.2"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.57"
structopt = { version = "0.3.13", default_features = false }
thiserror = "1.0.26"
tokio = { version = "1.11", features = ["macros"] }
tonic = "0.6.2"
tracing = "0.1"
url = "2.1.1"

[build-dependencies]
tonic-build = "0.6.2"

[dev-dependencies]
