[package]
name = "tari_utilities"
description = "A set of useful and commonly used utilities that are used in several places in the Tari project."
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2018"

[dependencies]
derive-error = "0.0.4"
clear_on_drop = "0.2.3"
chrono = { version = "0.4.9", features = ["serde"]}
bincode = "1.1.4"
base64 = "0.10.1"
serde_json = "1.0"
serde = {version = "1.0.102", features = ["derive"] }
rand = "0.7.2"
newtype-ops = "0.1.4"
bitflags = "1.2.1"

[dev-dependencies]
