[package]
name = "tari_infra_derive"
description = "Tari derive macros"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.8.2"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"
syn = "0.15.29"
blake2 = "0.8.0"
proc-macro2 =   "0.4.27"
