[package]
name = "keymanager"
version = "0.0.2"
edition = "2018"

[dependencies]
tari_crypto = { path = "../../infrastructure/crypto"}
tari_utilities = { path = "../../infrastructure/tari_util"}
rand = "0.5.5"
digest = "0.8.0"
sha2 = "0.8.0"
derive-error = "0.0.4"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

