# Config for launchpad v0.0.2
[common]
network = "dibbler"
message_cache_size = 10
message_cache_ttl = 1440
denylist_ban_period = 1440
buffer_rate_limit_console_wallet = 1000
dedup_cache_capacity = 25000
rpc_max_simultaneous_sessions = 1000

[common.igor]
peer_seeds = [
    # igor
    "8e7eb81e512f3d6347bf9b1ca9cd67d2c8e29f2836fc5bd608206505cc72af34::/onion3/l4wouomx42nezhzexjdzfh7pcou5l7df24ggmwgekuih7tkv2rsaokqd:18141",
    "00b35047a341401bcd336b2a3d564280a72f6dc72ec4c739d30c502acce4e803::/onion3/ojhxd7z6ga7qrvjlr3px66u7eiwasmffnuklscbh5o7g6wrbysj45vid:18141",
    "40a9d8573745072534bce7d0ecafe882b1c79570375a69841c08a98dee9ecb5f::/onion3/io37fylc2pupg4cte4siqlsmuszkeythgjsxs2i3prm6jyz2dtophaad:18141",
    "126c7ee64f71aca36398b977dd31fbbe9f9dad615df96473fb655bef5709c540::/onion3/6ilmgndocop7ybgmcvivbdsetzr5ggj4hhsivievoa2dx2b43wqlrlid:18141",
]

dns_seeds =["seeds.igor.tari.com"]
dns_seeds_use_dnssec = false

[common.dibbler]
dns_seeds =["seeds.dibbler.tari.com"]
peer_seeds = [
    "721e9da488302e69523bca1a9cdcbd2419dddda11698a1e8c6c7bd619659ff21::/onion3/qw4ymrzbanbcr3wwlesxbot72iayd7xdjcrtnacbwgk637vfon47hqad:18141",
    # 333388d1cbe3e2bd17453d052f
    "c2eca9cf32261a1343e21ed718e79f25bfc74386e9305350b06f62047f519347::/onion3/6yxqk2ybo43u73ukfhyc42qn25echn4zegjpod2ccxzr2jd5atipwzqd:18141",
    # 555575715a49fc242d756e52ca
    "42fcde82b44af1de95a505d858cb31a422c56c4ac4747fbf3da47d648d4fc346::/onion3/2l3e7ysmihc23zybapdrsbcfg6omtjtfkvwj65dstnfxkwtai2fawtyd:18141",
    # 77771f53be07fab4be5f1e1ff7
    "50e6aa8f6c50f1b9d9b3d438dfd2a29cfe1f3e3a650bd9e6b1e10f96b6c38f4d::/onion3/7s6y3cz5bnewlj5ypm7sekhgvqjyrq4bpaj5dyvvo7vxydj7hsmyf5ad:18141",
    # 9999016f1f3a6162dddf5a45aa
    "36a9df45e1423b5315ffa7a91521924210c8e1d1537ad0968450f20f21e5200d::/onion3/v24qfheti2rztlwzgk6v4kdbes3ra7mo3i2fobacqkbfrk656e3uvnid:18141",
    # bbbb8358387d81c388fadb4649
    "be128d570e8ec7b15c101ee1a56d6c56dd7d109199f0bd02f182b71142b8675f::/onion3/ha422qsy743ayblgolui5pg226u42wfcklhc5p7nbhiytlsp4ir2syqd:18141",
    # eeeeb0a943ed143e613a135392
    "3e0321c0928ca559ab3c0a396272dfaea705efce88440611a38ff3898b097217::/onion3/sl5ledjoaisst6d4fh7kde746dwweuge4m4mf5nkzdhmy57uwgtb7qqd:18141"
]

[base_node]
network = "dibbler"
grpc_enabled = true
grpc_address = "/ip4/0.0.0.0/tcp/18142"
track_reorgs = true

[base_node.dibbler]
db_type = "lmdb"
flood_ban_max_msg_count = 10000
allow_test_addresses = false
use_libtor = false
base_node_identity_file = "/var/tari/base_node/config/dibbler/tari_base_node_id.json"
base_node_tor_identity_file = "/var/tari/base_node/config/dibbler/tari_base_node_tor.json"

# -- These values are overridden by envars in the Tauri code for EVERY network
transport = "tor"
tor_control_auth = "password=tari"
tor_forward_address = "/dns4/base_node/tcp/18189"
tcp_listener_address = "/dns4/base_node/tcp/18189"
tor_socks_address_override = "/dns4/tor/tcp/9050"
tor_control_address = "/ip4/tor/tcp/9051"
grpc_enabled = true
grpc_base_node_address = "0.0.0.0:18142"


[base_node.igor]
db_type = "lmdb"
flood_ban_max_msg_count = 10000
allow_test_addresses = false
use_libtor = false
base_node_identity_file = "/var/tari/base_node/config/igor/base_node_id.json"
base_node_tor_identity_file = "/var/tari/base_node/config/igor/tari_base_node_tor.json"


[mempool.dibbler]

[mempool.igor]

[wallet]
wallet_db_file = "wallet/wallet.dat"
console_wallet_db_file = "wallet/console-wallet.dat"
grpc_enabled = true
grpc_address = "/ip4/0.0.0.0/tcp/18143"
password = "tari"

[wallet.dibbler]
use_libtor = false
tor_onion_port = 18141

# Overidden in Tauri environment variables for ALL networks
transport = "tor"
tor_control_auth = "password=tari"
tor_control_address = "/ip4/tor/tcp/9051"
tor_socks_address_override = ""
tor_forward_address = ""
tcp_listener_address= ""

[wallet.igor]
use_libtor = false
tor_onion_port = 18141

[mining_node]
num_mining_threads=1
base_node_grpc_address = "/ip4/base_node/tcp/18142"
wallet_grpc_address = "/ip4/wallet/tcp/18143"
base_node_addr = "/ip4/base_node/tcp/18142"
wallet_addr = "/ip4/wallet/tcp/18143"
mine_on_tip_only = true

[merge_mining_proxy.dibbler]
monerod_url = [ # stagenet
    "http://stagenet.xmr-tw.org:38081",
    "http://stagenet.community.xmr.to:38081",
    "http://monero-stagenet.exan.tech:38081",
    "http://xmr-lux.boldsuck.org:38081",
    "http://singapore.node.xmr.pm:38081",
]
proxy_host_address = "/ip4/mm_proxy/tcp/7878"

[merge_mining_proxy]

[stratum_transcoder]
transcoder_host_address = "127.0.0.1:7879"

[validator_node]
committee = ["2ea0df3059caf4411624d6bf5b9c02238d607d2798c586b3e6c2a054da3f205a"] # cannot be of zero size
phase_timeout = 30
template_id = "EditableMetadata"
