[package]
name = "tari_hashing"
version = "1.0.0-pre.11a"
edition = "2021"
description = "Tari hash domains"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_crypto = "0.20.0"
digest = "0.10"
borsh = "1.2"

[dev-dependencies]
blake2 = "0.10"