[package]
name = "minotari_ledger_wallet_common"
version = "1.1.0-pre.2"
authors = ["The Tari Development Community"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
tari_utilities = { version = "0.7", default-features = false }
bs58 = { version = "0.5.1", default-features = false, features = ["alloc"] }