[package]
name = "tari_dan_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_common_types = { path = "../../base_layer/common_types" }
tari_common = { path = "../../common" }
tari_dan_common_types = { path = "../common_types" }
tari_mmr = { path = "../../base_layer/mmr" }
tari_utilities = { git = "https://github.com/tari-project/tari_utilities.git", tag = "v0.4.4" }
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", tag = "v0.15.1" }
tari_template_abi = { path = "../template_abi" }

anyhow = "1.0.53"
borsh = "0.9.3"
cargo_toml = "0.11.5"
d3ne = { git = "https://github.com/stringhandler/d3ne-rs.git", branch = "st-fixes2" }
digest = "0.9.0"
log = { version = "0.4.8", features = ["std"] }
rand = "0.8.1"
serde = "1.0.126"
serde_json = "1.0.81"
thiserror = "^1.0.20"
wasmer = "2.3.0"
