[package]
name = "merklemountainrange"
description = "A general Merkle Mountain Range implementation and API"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.1"
edition = "2018"

[dependencies]
tari_utilities = { path = "../tari_util", version = "^0.0" }
derive-error = "0.0.4"
digest = "0.8.0"

[dev-dependencies]
blake2 = "0.8.0"
