[package]
name = "test_faucet"
version = "0.29.0"
authors = ["The Tari Development Community"]
edition = "2018"
license = "BSD-3-Clause"

[features]
simd = ["tari_crypto/simd"]
avx2 = ["simd"]

[dependencies]
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }
tari_utilities = { git = "https://github.com/tari-project/tari_utilities.git", branch = "main" }
tari_common_types = { path = "../../base_layer/common_types" }

rand = "0.8"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0"

[dependencies.tari_core]
path = "../../base_layer/core"
default-features = false
features = ["transactions"]

[dependencies.tokio]
version = "^1.10"
default-features = false
features = ["fs", "rt-multi-thread", "macros", "io-util", "sync"]
