on:
  push:
    branches:
      - development

name: Deploy RFC Docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install ğŸ¦€
        run: |
          curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v0.10.0/mdbook-mermaid-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar xvz
          cd RFC
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.8/mdbook-v0.4.8-x86_64-unknown-linux-gnu.tar.gz | tar xvz

      - name: Build ğŸ› 
        run: |
          cd RFC
          ./mdbook test
          ./mdbook build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: book
          commit-message: "[skip ci] deploy gh-pages"
