[package]
name = "minotaiji_mining_helper_ffi"
authors = ["The Taiji Development Community"]
description = "Taiji cryptocurrency miningcore C FFI bindings"
license = "BSD-3-Clause"
version = "0.52.0-pre.0"
edition = "2018"

[dependencies]
taiji_comms = {  path = "../../comms/core" }
tari_crypto = { version = "0.18" }
taiji_common = {  path = "../../common" }
taiji_core = {  path = "../core", default-features = false, features = ["transactions"]}
tari_utilities = { version = "0.5" }
libc = "0.2.65"
thiserror = "1.0.26"
borsh = "0.10"
hex = "0.4.2"

[dev-dependencies]
taiji_core = { path = "../core", features = ["transactions", "base_node"]}

rand = "0.8"

[lib]
crate-type = ["staticlib","cdylib"]
