[package]
name = "tari_comms"
description = "A peer-to-peer messaging system"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.1"
edition = "2018"

[dependencies]
clear_on_drop = "0.2.3"
derive-error = "0.0.4"
rand = "0.5.5"
tari_crypto = { path = "../crypto"}
tari_utilities = { path = "../../infrastructure/tari_util"}
zmq = "0.9"
chrono ="0.4.6"
bitflags ="1.0.4"
serde = "1.0.90"
serde_derive = "1.0.90"

[dev-dependencies]
rmp-serde = "0.13.7"
